### ISSUE TITLE
these login methods do not work on your site 

### ISSUE THREAD

**Issue by samayo** [tyler-sommer/TylerSommerdotcom#1]
I am trying to learn more about the HWI oauth, and I looked at your blog, but tried to login via twitter/github and they don't  work, I get errors from both sides .. is there anything you might have missed?

**Comment by tyler-sommer** [comment]
Hi @samayo, thanks for bringing this to my attention! The issue you're seeing is an error unrelated to OAuth, but I won't be able to resolve it immediately. I'll update this ticket when I fix the issue so you can see it working. In the meantime, if you have any questions I'm more than happy to help. Feel free to reach out via email, too. Cheers!

**Comment by tyler-sommer** [comment]
@samayo, I've fixed [the issue](https://github.com/tyler-sommer/TylerSommerdotcom/commit/4db17f88926e2822c48a47d795a396d24d8f353d) and you should be able to login with Twitter or GitHub.

Let me know if you have any further questions. Cheers!
